{
 "title": "AproxM - Evidencia 3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Valor Actual", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Valor actual",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AproxMT_ev3",
     "rawSql": "SELECT bpm FROM AproxMT_ev3.heart_rate ORDER BY id DESC LIMIT 1 "
    }
   ]
  },
  { "title": "Información Procesada", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Valor Mínimo Registrado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AproxMT_ev3",
     "rawSql": "SELECT MIN(bpm) FROM AproxMT_ev3.heart_rate LIMIT 50 "
    }
   ]
  },
  {
   "title": "Valor Promedio de los registros",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AproxMT_ev3",
     "rawSql": "SELECT AVG(bpm) FROM AproxMT_ev3.heart_rate GROUP BY bpm "
    }
   ]
  },
  {
   "title": "Valor Máximo Registrado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AproxMT_ev3",
     "rawSql": "SELECT MAX(bpm) FROM AproxMT_ev3.heart_rate LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total de Valores Registrados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AproxMT_ev3",
     "rawSql": "SELECT COUNT(bpm) FROM AproxMT_ev3.heart_rate LIMIT 50 "
    }
   ]
  },
  { "title": "Historial de Registros", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Tabla BPM (Base de datos MySQL)",
   "type": "table",
   "description": "latidos por minutos",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "AproxMT_ev3",
     "rawSql": "SELECT id AS \"Número de registro\", bpm AS \"BPM (latidos por minutos)\" FROM AproxMT_ev3.heart_rate ORDER BY id DESC "
    }
   ]
  },
  {
   "title": "Histograma de BPM",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "AproxMT_ev3",
     "rawSql": "SELECT bpm FROM AproxMT_ev3.heart_rate "
    }
   ]
  }
 ]
}